[package]
name = "proctor"
version = "0.1.0"
authors = ["Damon Rolfs <drolfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "proctor"
path = "src/main.rs"

[[example]]
name = "sandbox"
path = "examples/sandbox.rs"

[[example]]
name = "config"
path = "examples/config.rs"

[[example]]
name = "eth-scan"
path = "examples/eth_scan.rs"

[[example]]
name = "async-stream"
path = "examples/async_stream.rs"

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1"
chrono = "0.4"
config = { version = "0.10", default-features = false, features = ["toml", "hjson"] }
derive_more = "0.99"
futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"
lazy_static = "1.4"
num_cpus = "1.13"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = "1"
serde_json = "1"
serde-aux = "2.1"
sonyflake = "0.1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-bunyan-formatter = "0.1"
tracing-futures = "0.2"
tracing-log = "0.1"
tracing-subscriber = "0.2"
uuid = { version = "0.8", features = ["serde", "v4"] }
pin-project = "1"
pin-project-lite = "0.2"
enum-display-derive = "0.1"
rand = "0.8"
oso = "0.11.0"
app_data_derive = { path = "app_data_derive" }
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
csv = "1.1"
toml = "0.5.8"
cast_trait_object = "0.1.3"
#serde_with = { version = "1.6.4", features = ["chrono", "json", "macros"] }

[dev-dependencies]
serde_test = "1"
tokio-test = "0.4"
maplit = "1"
criterion = { version = "0.3", features = ["async_tokio", "html_reports"] }

[[bench]]
name = "bench_main"
harness = false

