[package]
name = "proctor"
version = "0.1.0"
authors = ["Damon Rolfs <drolfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "proctor"
path = "src/main.rs"

[[example]]
name = "sandbox"
path = "examples/sandbox.rs"

[[example]]
name = "config"
path = "examples/config.rs"

[[example]]
name = "eth-scan"
path = "examples/eth_scan.rs"

[[example]]
name = "async-stream"
path = "examples/async_stream.rs"

[dependencies]
anyhow = "*"
async-stream = "*"
async-trait = "*"
chrono = "*"
config = { version = "*", default-features = false, features = ["toml", "hjson"] }
derive_more = "*"
futures = "*"
futures-core = "*"
futures-util = "*"
lazy_static = "*"
num_cpus = "*"
reqwest = { version = "*", features = ["blocking", "json"] }
serde = "*"
serde_json = "*"
flexbuffers = "*"
serde-aux = "*"
thiserror = "*"
tokio = { version = "*", features = ["full"] }
tokio-stream = "*"
tracing = "*"
tracing-bunyan-formatter = "*"
tracing-futures = "*"
tracing-log = "*"
tracing-subscriber = "*"
tracing-flame = "*"
uuid = { version = "*", features = ["serde", "v4"] }
pin-project = "*"
pin-project-lite = "*"
enum-display-derive = "*"
rand = "*"
oso = "*"
polar-core = "*"
proctor_derive = { path = "proctor_derive" }
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
csv = "*"
toml = "*"
cast_trait_object = "*"
serde_with = { version = "*", features = ["chrono", "json", "macros"] }
maplit = "*"
regex = "*"
itertools = "*"
#smartcore = { version = "*", features=["nalgebra-bindings"]}
#nalgebra = ">=0.27.1"
statrs = "*"

[dev-dependencies]
serde_test = "1"
tokio-test = "0"
criterion = { version = "0", features = ["async_tokio", "html_reports"] }
pprof = {version = "0", features = ["flamegraph"]}
static_assertions = "1"
pretty_assertions = "0"


[[bench]]
name = "bench_main"
harness = false

