[package]
name = "proctor"
version = "0.1.0"
authors = ["Damon Rolfs <drolfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "proctor"
path = "src/main.rs"

[[example]]
name = "sandbox"
path = "examples/sandbox.rs"

[[example]]
name = "config"
path = "examples/config.rs"

[[example]]
name = "eth-scan"
path = "examples/eth_scan.rs"

[[example]]
name = "async-stream"
path = "examples/async_stream.rs"

[dependencies]
anyhow = "1"
async-stream = "0"
async-trait = "0"
chrono = "0"
config = { version = "0", default-features = false, features = ["toml", "hjson"] }
derive_more = "0"
futures = "0"
futures-core = "0"
futures-util = "0"
lazy_static = "1"
num_cpus = "1"
reqwest = { version = "0", features = ["blocking", "json"] }
serde = "1"
serde_json = "1"
serde_cbor = "0"
serde-aux = "2"
sonyflake = "0"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0"
tracing = "0"
tracing-bunyan-formatter = "0"
tracing-futures = "0"
tracing-log = "0"
tracing-subscriber = "0"
uuid = { version = "0", features = ["serde", "v4"] }
pin-project = "1"
pin-project-lite = "0"
enum-display-derive = "0"
rand = "0"
oso = "0"
polar-core = "0"
proctor_derive = { path = "proctor_derive" }
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
csv = "1"
toml = "0"
cast_trait_object = "0"
#serde_with = { version = "1.6.4", features = ["chrono", "json", "macros"] }
maplit = "1"
serde-name = "0"
regex = "1.4.6"

[dev-dependencies]
serde_test = "1"
tokio-test = "0"
criterion = { version = "0", features = ["async_tokio", "html_reports"] }
static_assertions = "1"

[[bench]]
name = "bench_main"
harness = false

