[package]
name = "proctor"
version = "0.1.0"
authors = ["Damon Rolfs <drolfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[example]]
name = "sandbox"
path = "examples/sandbox.rs"

[[example]]
name = "config"
path = "examples/config.rs"

[[example]]
name = "eth-scan"
path = "examples/eth_scan.rs"

[[example]]
name = "async-stream"
path = "examples/async_stream.rs"

[dependencies]
anyhow = "*"
approx = "*"
async-stream = "*"
async-trait = "*"
cast_trait_object = "*"
chrono = "*"
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
config = { version = "*", default-features = false, features = ["toml", "hjson"] }
csv = "*"
enum-display-derive = "*"
flexbuffers = "*"
futures = "*"
futures-util = "*"
lazy_static = "*"
num_cpus = "*"
oso = "*"
polar-core = "*"
proctor_derive = { path = "proctor_derive" }
reqwest = { version = "*", features = ["blocking", "json"] }
serde = "*"
serde_json = "*"
statrs = "*"
thiserror = "*"
tokio = { version = "*", features = ["full"] }
toml = "*"
tracing = "*"
tracing-bunyan-formatter = "*"
tracing-flame = "*"
tracing-futures = "*"
tracing-log = "*"
tracing-subscriber = "*"

[dev-dependencies]
claim = "*"
criterion = { version = "*", features = ["async_tokio", "html_reports"] }
futures-core = "*"
itertools = "*"
maplit = "*"
pprof = {version = "*", features = ["flamegraph"]}
pretty_assertions = "*"
rand = "*"
serde_test = "*"
serde_with = { version = "*", features = ["chrono", "json", "macros"] }
tokio-test = "*"

[[bench]]
name = "bench_main"
harness = false
