[package]
name = "proctor"
version = "0.8.0"
authors = ["Damon Rolfs <drolfs@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[example]]
name = "sandbox"
path = "examples/sandbox.rs"

[[example]]
name = "eth-scan"
path = "examples/eth_scan.rs"

[[example]]
name = "async-stream"
path = "examples/async_stream.rs"

[dependencies]
anyhow = "1.0.51"
approx = "0.5.0"
async-stream = "0.3.2"
async-trait = "0.1.52"
cast_trait_object = "0.1.3"
chrono = "0.4.19"
clap = { version = "3.0.0-rc.7", features = ["yaml"] }
config = "0.11.0"
#config = { git = "https://github.com/dmrolfs/config-rs" }
csv = "1.1.6"
either = { version = "1.6.1", features = ["serde"] }
enum-display-derive = "0.1.1"
flexbuffers = "2.0.0"
futures = "0.3.17"
futures-util = "0.3.17"
handlebars = "4.1.6"
maplit = "1.0.2"
num_cpus = "1.13.0"
num-traits = "0.2.14"
once_cell = "1.9.0"
oso = "0.24.0"
polar-core = "0.24.0"
pretty-snowflake = { git = "https://github.com/dmrolfs/pretty-snowflake-rs" }
proctor_derive = { path = "proctor_derive" }
prometheus = { version = "0.13.0", features = ["process"] }
prometheus-static-metric = "0.5.1"
regex = "1.5.4"
reqwest = { version = "0.11.7", features = ["blocking", "json"] }
reqwest-middleware = "0.1.3"
reqwest-retry = "0.1.3"
ron = "0.7.0"
serde = "1.0.132"
serde_json = "1.0.73"
statrs = "0.15.0"
tempfile = "3.2.0"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["full"] }
tracing = "0.1.29"
tracing-bunyan-formatter = "0.3.1"
tracing-flame = "0.2.0"
tracing-futures = "0.2.5"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3.3", features = ["env-filter", "json"] }
trim-margin = "0.1.0"
url = "2.2.2"
validator = { version = "0.14.0", features = ["derive"] }

[dev-dependencies]
claim = "0.5.0"
criterion = { version = "0.3.5", features = ["async_tokio", "html_reports"] }
futures-core = "0.3.17"
itertools = "0.10.3"
pprof = { version = "0.6.1", features = ["flamegraph"] }
pretty_assertions = "1.0.0"
rand = "0.8.4"
serde_test = "1.0.132"
serde-transcode = "1.1.1"
serde_with = { version = "1.11.0", features = ["chrono", "json", "macros"] }
static_assertions = "1.1.0"
tokio-test = "0.4.2"

[[bench]]
name = "bench_main"
harness = false
